### ISSUE TITLE
Ticker Object Empty

### ISSUE THREAD

**Issue by bbell03** [bvkin/trade_bot#32]
any idea why the ticker object is NoneType on run in this example?

(base) brandonbell@MacBook-Air trade_bot % python trade_bot/main.py --strategy=MovingAverages
<core.alpaca.alpaca_trade_manager.AlpacaTradeManager object at 0x13ee5f3d0>
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:Running order scheduler...
INFO:root:Making orders...
Traceback (most recent call last):
  File "/Users/brandonbell/Desktop/trade_bot/trade_bot/main.py", line 49, in <module>
    make_orders(trade_manager, strat, args.tickers, sns_client, sns_topic_arn)
  File "/Users/brandonbell/anaconda3/lib/python3.10/site-packages/trade_bot/make_orders.py", line 20, in make_orders
    for ticker in tickers:
TypeError: 'NoneType' object is not iterable

**Comment by bbell03** [comment]
Tickers must be passed explicitly
