### ISSUE TITLE
Different Behavior Across "python" and "python3" commands

### ISSUE THREAD

**Issue by bbell03** [bvkin/trade_bot#33]
python trade_bot/main.py --strategy=MovingAverages
<core.alpaca.alpaca_trade_manager.AlpacaTradeManager object at 0x13205b370>
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:Running order scheduler...
INFO:root:Making orders...
Traceback (most recent call last):
  File "/Users/brandonbell/Desktop/trade_bot/trade_bot/main.py", line 49, in <module>
    make_orders(trade_manager, strat, args.tickers, sns_client, sns_topic_arn)
  File "/Users/brandonbell/anaconda3/lib/python3.10/site-packages/trade_bot/make_orders.py", line 20, in make_orders
    for ticker in tickers:
TypeError: 'NoneType' object is not iterable

(base) brandonbell@MacBook-Air trade_bot % python3 trade_bot/main.py --strategy=MovingAverages
Traceback (most recent call last):
  File "/Users/brandonbell/Desktop/trade_bot/trade_bot/main.py", line 4, in <module>
    from core.trading.moving_averages import MovingAverages
  File "/Users/brandonbell/Desktop/trade_bot/trade_bot/core/trading/moving_averages.py", line 6, in <module>
    from talib import SMA
ModuleNotFoundError: No module named 'talib'

**Comment by bbell03** [comment]
Um so this could be like a noob thing and it has to do with what version of python I'm using so I'll try updating the one that runs with python3
